const projects = [
        { 
          title: "Basic Crew Neck Tee",
          imageUrl: "../public/image/Basic_Crew_Neck_Tee.png",
          excerpt: "Black",
          price: '$44.00',
          label: 'New',
        },
        {
          title: "Basic Crew Neck Tee",
          imageUrl: "../public/image/Basic_Crew_02.png",
          excerpt: "Black",
          price: '$44.00',
          label: 'New',
        },
        {
          title: "Basic Crew Neck Tee",
          imageUrl: "../public/image/Basic_Crew_03.png",
          excerpt: "Black",
          price: '$44.00',
          label: 'New',
        },
        {
          title: "Basic Crew Neck Tee",
          imageUrl: "../public/image/Basic_Crew_04.png",
          excerpt: "Black",
          price: '$44.00',
          label: '-15%',
        },
        {
          title: "Basic Crew Neck Tee",
          imageUrl: "../public/image/Basic_Crew_Neck_Tee.png",
          excerpt: "Black",
          price: '$44.00',
          label: 'New',
        },
        {
          title: "Basic Crew Neck Tee",
          imageUrl: "../public/image/Basic_Crew_04.png",
          excerpt: "Black",
          price: '$44.00',
          label: '-10%',
        },
        {title:"Basic Crew Neck Tee",
        excerpt:"Black",
        imageUrl:"../public/image/Special_Offers_05.png",
        price:"$44.00",
        label:'New'
        },
        {title:"Basic Crew Neck Tee",
        excerpt:"Black",
        imageUrl:"../public/image/Special_Offers_06.png",
        price:"$44.00",
        label:'New'
        },
        {title:"Basic Crew Neck Tee",
        excerpt:"Black",
        imageUrl:"../public/image/Special_Offers_07.png",
        price:"$44.00",
        label:'New'
        },
        {title:"Basic Crew Neck Tee",
        excerpt:"Black",
        imageUrl:"../public/image/Special_Offers_02.png",
        price:"$44.00",
        label:'New'
        },
        {title:"Basic Crew Neck Tee",
        excerpt:"Black",
        imageUrl:"../public/image/Special_Offers_04.png",
        price:"$44.00",
        label:'New'
        },
        {title:"Basic Crew Neck Tee",
        excerpt:"Black",
        imageUrl:"../public/image/Special_Offers_06.png",
        price:"$44.00",
        label:'New'
        },
        {title:"Basic Crew Neck Tee",
        excerpt:"Black",
        imageUrl:"../public/image/Special_Offers_06.png",
        price:"$44.00",
        label:'New'
        },
        {title:"Basic Crew Neck Tee",
        excerpt:"Black",
        imageUrl:"../public/image/Special_Offers_06.png",
        price:"$44.00",
        label:'New'
        },
      ];
export default projects
